=== rogowskibart/tin/zadanie-12/tweet.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="tweet">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="id">
          <xs:unique name="id_unique" >
            <xs:selector xpath="id" />
            <xs:field xpath="." />
          </xs:unique>
        </xs:element>
        <xs:element name="author">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:pattern value='@[a-zA-Z\d_]{5,15}' />
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="date" type="xs:date" />
        <xs:element name="numberOfRetweets" type="xs:integer"/>
        <xs:element name="numberOfQuotes" type="xs:integer"/>
        <xs:element name="numberOfLikes" type="xs:integer"/>
        <xs:element name="length">
          <xs:simpleType>
            <xs:restriction base="xs:integer">
              <xs:minExclusive value="0" />
              <xs:maxInclusive value="140" />
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="location">
          <xs:simpleType>
            <xs:list>
              <xs:simpleType>
                <xs:union memberTypes="latitude longitude" />
              </xs:simpleType>
            </xs:list>
          </xs:simpleType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:simpleType name="latitude">
      <xs:restriction base="xs:decimal">
        <xs:maxInclusive value="90" />
        <xs:minInclusive value="-90" />
      </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="longitude">
    <xs:restriction base="xs:decimal">
        <xs:maxInclusive value="180" />
        <xs:minInclusive value="-180" />
      </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== rogowskibart/tin/zadanie-12/tweet.xml
<?xml version="1.0"?>

<tweet xsi:noNamespaceSchemaLocation="tweet.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <id>156</id>
  <author>@author</author>
  <date>2021-06-12</date>
  <privacy>everyone</privacy>
  <numberOfRetweets>213</numberOfRetweets>
  <numberOfQuotes>51</numberOfQuotes>
  <numberOfLikes>1233</numberOfLikes>
  <length>132</length>
</tweet>
